server:
  port: 8080

spring:
  application:
    name: SkillVaultBackend
  datasource:
    url: jdbc:postgresql://localhost:5432/Skill-Vault
    username: postgres
    password: "0000"
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

skillvault:
  content:
    path: "../content"
